services:
  backend:
    build:
      context: ..
      dockerfile: ./deploy/prod.Dockerfile
    env_file:
      - ../config/backend.env
    networks:
      - net
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:18-alpine
    env_file:
      - ../config/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - net
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  net:
    name: net
    driver: bridge
